### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by Vinnl** [inrupt/jose-legacy-modules-js#6]
@NSeydoux The builds are consistently failing (looks like a new release that removed a module that is being exported?) - I get an email every time that happens. Might want to figure out how to get it to email someone else, and to fix the issue :P

**Comment by NSeydoux** [comment]
Haha I knew the builds were failing due to a changed export, but I got the notification from `@inrupt/solid-client-authn`, and didn't realize this repo would keep notifying you, sorry about that ^^
